### PR TITLE
adding missing argument "user_attributes" for feature flags variables

### PR DESCRIPTION
**Pull request by peqp1988**
### Change
adding missing argument `user_attributes` for feature flags

### CODE REVIEW

**Comment by patriciapineda** [comment]
@ankit8898  @gouravtiwari @Manpreet-kaur

**Comment by manpreet141987** [comment]
LGTM 👍

**Review by manpreet141987 — APPROVED** [review]

**Comment by ankit8898** [comment]
@Manpreet-kaur @patriciapineda Going through the [feature-variables](https://docs.developers.optimizely.com/full-stack/docs/define-feature-variables) doc I see that the parameter is a `user_id` while we are passing `user_attributes` (hash). Will things work as expected?

Screen Shot 2019-03-11 at 10 46 12 PM

**Comment by manpreet141987** [comment]
@ankit8898 Its actually a map (hash) https://docs.developers.optimizely.com/full-stack/docs/get-feature-variable

image

The example that you gave is when we are invoking the method, the change is in the method definition which accepts the hash for the attributes.

**Comment by ankit8898** [comment]
> @ankit8898 Its actually a map (hash) https://docs.developers.optimizely.com/full-stack/docs/get-feature-variable
> 
> image
> 
> The example that you gave is when we are invoking the method, the change is in the method definition which accepts the hash for the attributes :)

Thanks for clarification!

**Comment by ankit8898** [comment]
@Manpreet-kaur @patriciapineda [version 2.0.1](https://rubygems.org/gems/optimizely_server_side/versions/2.0.1) is published. Thanks again for changes! 🙌

**Comment by manpreet141987** [comment]
Thank you Ankit !! 👍

**Comment by peqp1988** [comment]
> @Manpreet-kaur @patriciapineda [version 2.0.1](https://rubygems.org/gems/optimizely_server_side/versions/2.0.1) is published. Thanks again for changes! 🙌

thank you Ankit!

**Pull request merged**
